### ISSUE TITLE
rename deis endpoint to workflow

### ISSUE THREAD

**Issue by bacongobbler** [deis/router#141]
related to https://github.com/deis/deis/issues/4952. Since the project is being renamed from `deis` to `workflow`, the router endpoint should now read `workflow.mydomain.com` instead of `deis.mydomain.com`.

**Comment by helgi** [comment]
Since the CLI is not being changed, does this need to be changed?

**Comment by mboersma** [comment]
It's workflow, but it's still the Deis workflow. I feel that "deis" is sort of grandfathered in for a couple purposes, including the `deis` CLI and (I would argue) this canonical API endpoint. 

My other argument being that I type this often and now that I've finally stopped typing "dies" all the time, I know changing to "workflow" will cost me milliseconds. :smile:

**Comment by bacongobbler** [comment]
To be clear, this is to demonstrate points which need discussion in deis/deis#4952. I'm not proposing that we change the name, just opening it up for discussion and visibility in that meta ticket.

**Comment by bacongobbler** [comment]
@helgi see deis/workflow-cli#20. This was never discussed in deis/deis#4952 so I've brought that point up.

**Comment by krancour** [comment]
Good discussion.  I think I agree with it being changed to "workflow," but that's just because, I still worry that we do ourselves a disservice if we're not 100% consistent in differentiating the brand from the product.  Having said that, I'm commenting less to argue in its favor than to note that if we were to follow through with this, it should actually be a change to the charts.  Router has no built-in or special knowledge of workflow or its primary component-- controller.  We can, however, keep the discussion here.

**Comment by krancour** [comment]
Discussed this this morning in the standup and this won't be renamed.  Closing.
