### ISSUE TITLE
router/certificates only work with full domains

### ISSUE THREAD

**Issue by jcmoraisjr** [deis/router#164]
The annotation `router.deis.io/domains` does work as expected if the domain doesn't have any dot `.`: such domain will be a subdomain of `router.deis.io/nginx.platformDomain` defined in the router annotation.

I tried to configure https using this same approach but the configuration didn't work. Eg:

**This works:**

* Router RC:
    * `router.deis.io/nginx.platformDomain: "example.com"`
* Routable app:
    * `router.deis.io/domains: "bar"`

Http is configured as `bar.example.com`

**This also works:**

* Router RC:
    * `router.deis.io/nginx.platformDomain: "example.com"`
* Routable app:
    * `router.deis.io/domains: "bar.example.com"`
    * `router.deis.io/certificates: "bar.example.com:bar"`

Both http and https are configured as `bar.example.com`. The cert and key declared in `secret/bar-cert` are used as expected.

**This does not work:**

* Router RC:
    * `router.deis.io/nginx.platformDomain: "example.com"`
* Routable app:
    * `router.deis.io/domains: "bar"`
    * `router.deis.io/certificates: "bar:bar"`

Http is configured and https is ignored.

**Comment by krancour** [comment]
@jcmoraisjr I think you may have uncovered an edge case we didn't anticipate.  I usually anticipate that if anyone is doing HTTPS on a subdomain of the platform domain, they are providing a wildcard certificate for the platform domain as described here: https://github.com/deis/router#platform-certificate

That being said, I'm debating in my own head whether your use case is valid.  On the one hand, wildcard certs are expensive and are also prohibited by some organizations.  I easily can see a scenario where someone wants to use specific (non-wildcard) certs for specific apps on specific subdomains only and _not_ use a wildcard cert for the whole cluster.

But on the other hand, I believe the least ambiguous way to do that is by doing what you have noted already works:

> * Router RC:
    * router.deis.io/nginx.platformDomain: "example.com"
* Routable app:
    * router.deis.io/domains: "bar.example.com"
    * router.deis.io/certificates: "bar.example.com:bar"

Suppose that what doe not work _did_:

> * Router RC:
    * router.deis.io/nginx.platformDomain: "example.com"
* Routable app:
    * router.deis.io/domains: "bar"
    * router.deis.io/certificates: "bar:bar"

In this second scenario, if the platform domain changes from `example.com` to `forinstance.com`, your app with the "domain" `bar` moves to `https://bar.forinstance.com`, but users will see a cert warning because the `bar-cert` is still a certificate for `https://bar.example.com`

This is a roundabout way of saying that the first scenario seems more clear cut than the second because it explicitly associates a cert to a domain, whereas the second associates a cert to something relative.

Again... I can see some validity to the use case, but I think that introducing support for the second scenario gives users more rope to hang themselves with than if they observed the pattern of the first scenario.

Does this make any sort of sense?

**Comment by jcmoraisjr** [comment]
Depending on the way I see the `router.deis.io/nginx.platformDomain` annotation, I'd understand this question in a different way. My understanding is that the `platformDomain` annotation is something you cannot change without breaking external links. In my opinion the invalid cert is just one of the problems that would arise. 

Thinking about the semantics. In my head `router.deis.io/nginx.platformDomain` dictates the domain this router is using. If one don't want it one may ignore it. Using dotted subdomains is already a big plus as a way to ignore the `platformDomain`. Again, in my opinion, this behavior should be the same with `domains` and `certificates`.

You have valid points, but I'd advocate on behalf of consistency between domains and certificates. Anyway docs should be updated describing how subdomains are managed in both annotations -- cutting the rope before users hang themselves =)

**Comment by krancour** [comment]
> My understanding is that the platformDomain annotation is something you cannot change without breaking external links.  In my opinion the invalid cert is just one of the problems that would arise.

Well that's true, for sure.  There's a missing piece of this conversation though, which is the separation of roles inherent in most organizations.  Using the Google operational model as a point of reference, it defines the separation of developers, from app ops, from cluster ops.

Put the cluster ops hat on for a moment.  (So you're a Kubernetes admin, essentially.  It's unlikely, but _possible_ that you are not also a Deis Workflow admin.)  If you were to change the `platformDomain`, you may break things-- as you noted.  However, it's presumably within your power to avoid those breakages.  You'd be updating DNS to make `*.newdomain.com` point to wherever `*.olddomain.com` was pointing to, and if you were using a wildcard cert for the `platformDomain`, you'd also be changing that at that time as well.  These low-level operations can be done without impact to and without regard for any fully qualified domains and associated certificates that _app ops_ are managing.  (More on this in a bit.)

If you're an app ops guy or gal, you want to be able to associate fully qualified domains (which you presumably control DNS for) to your application and associate certificates to those domains.  You want to be able to do this _independently_ of the cluster ops guy or gal.  So if you're app ops and have associated `myapp.foo.com` to your app and have associated a `myapp.foo.com` cert to that domain, then when the cluster ops guy or gal changes things as described in the previous paragraph, he or she cannot break you.  (Assuming, of course, that users actually access your app through the custom / vanity domain.)

How these things can be done independently of one another probably bears some further explanation. This is where we start to get into opinionated territory re: how clusters should be managed, but based on my own experience and observation of others' clusters, the `platformDomains` you'd likely encounter in the wild are super ugly.  For example, `east.production.example.com`.  More than likely, the business owner of the `foo` application isn't going to care much for their users accessing the application via `https://foo.east.production.example.com`.  In response, app ops are likely to have associated `foo.example.com` to the application.  As a result, when cluster ops changes `east.production.example.com` to `region1.production.example.com`, there's zero fallout to the `foo` application.

But coming back to where this all started... allowing app ops to associate a certificate to a "domain" that's relative to the `platformDomain` probably shouldn't be done because it opens the door for cluster ops to break your app.

**Comment by krancour** [comment]
Closing this. I've let this marinate for a while and still feel strongly that the current behavior is correct and that modifying that would create opportunities for cluster ops to break apps without even knowing they'd done so.
