### ISSUE TITLE
Better error message when the controller is unavailable

### ISSUE THREAD

**Issue by kmala** [deis/router#174]
currently when the controller is down we get:
```Error: 
503 Service Temporarily Unavailable
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx/1.9.6</center>
</body>
</html>

**Comment by arschles** [comment]
@kmala @krancour if the controller returns a `503` with a descriptive response body, will nginx respect it and forward it to the client?

**Comment by krancour** [comment]
This issue is confusing to me.

@kmala if the controller goes down, "503 Service Temporarily Unavailable" is an accurate and correct error message, isn't it?  What more would you have it say?  Router treats the controller like "just another app."  Why should we treat it any differently?

@arschles the 503 doesn't come from the controller, it comes from the _absence_ of any controller pod.

**Comment by arschles** [comment]
>@arschles the 503 doesn't come from the controller, it comes from the absence of any controller pod.

This question stems from a discussion in deis/controller (I don't have the issue # handy) where we want the controller to stay up but return 503s when the database connection is severed. My question boils down to: if the controller is present and returns a `503` and the response body is `foo` (when the DB is unavailable to the controller), will the router forward `foo` to the client?

**Comment by kmala** [comment]
@krancour in this PR https://github.com/deis/controller/pull/678 i changing the readiness probe to check for database connectivity which means when the DB is down the Pod will be up but the service endpoint will not have its IP as it is not serviceable and it is not available returning a 503 is correct but @helgi  want to a something different error https://github.com/deis/controller/pull/678#issuecomment-215241936

**Comment by krancour** [comment]
> My question boils down to: if the controller is present and returns a 503 and the response body is foo (when the DB is unavailable to the controller), will the router forward foo to the client?

Yes.  Ultimately, the router is just a proxy for upstream applications.  As long as the router is able to communicate with those applications, what it will return to the end-user will be exactly what was returned from the app.  (Ok... technically, not _exactly_.  The router will gzip the response, for instance, but that's really not relevant here.)  That would include 503s issued by the controller, if that is how the controller chooses to deal with the condition where the database is down.

**Comment by krancour** [comment]
Ok.  Now re-reading @kmala's last comment, I think there are some conflicting things here.

> we want the controller to stay up but return 503s when the database connection is severed

If the controller is up, but returns 503s, the router can handle that just fine, as indicated by my previous comment.

> changing the readiness probe to check for database connectivity which means when the DB is down the Pod will be up but the service endpoint will not have its IP as it is not serviceable and since it is not available returning a 503

If the controller is considered not ready because it has lost connectivity to the database, the 503 doesn't come from the controller, but rather from the controller's svc.

In either case, the router is only going to return whatever response it got from upstream-- it doesn't matter whether that is the controller svc (with no pods backing it) or from the controller.

Ultimately, if better error messages are desired in the case of a loss of database connectivity, I believe the changes required to support that are isolated to the controller.  I don't foresee any need for router changes... unless I am missing something here... which has been known to happen.

**Comment by kmala** [comment]
@krancour  i am talking about the scenario of no pods backing the controller scenario....since there won't be any upstream endpoint i thought this has to be handled by the router as there is won't be any response coming from the controller

**Comment by krancour** [comment]
Discussed with @kmala and there isn't anything actionable for the router here, hence, closed.
