### ISSUE TITLE
Enable HTTPS routing for out of the box deis install

### ISSUE THREAD

**Issue by chicagozer** [deis/router#175]
The out of the box deis install with helm puts a self-signed cert on the deis router (deis.rocks). 

However, it doesn't appear the router will route any https:// application traffic without further configuration.

Can this be enabled without doing a full wildcard certificate install?

**Comment by krancour** [comment]
I can see where this might look like a convenience, but I don't think we should do this.  First, let me go on record as saying that I don't think shipping with a default, self-signed cert is actually a good thing-- it seems janky.  I wouldn't want to encourage further use of it.

The inclusion of the default self-signed cert is a necessary evil that we conceded to for one very specific reason.  See #136 and #139 for more info, but I'll summarize more succinctly here.

Consider the case where you have _some_ apps HTTPS enabled, but not others.  The corresponding Nginx config generated by the router will have _some_ virtualhosts listening on 443 (technically, 6443, but that's a story for another time), but not _all_.  Now, if an incoming request attempts to use HTTPS for an app that is _not_ HTTPS enabled, the request won't match _any_ of the vhosts, and as a result will fall to whichever is the "default" vhost listening on 443 (6443).  Unless explicitly defined, the default is the first vhost, alphabetically speaking.  The consequence of that had previously been that with two apps having domains `domain.one` HTTPS enabled and `domain.two` _not_ HTTPS enabled, respectively, requests to `https://domain.two` would not only yield a cert error, but if ignored, would also yield a _response / content_ from the wrong app (`domain.one`).

To circumvent that surprising and obviously undesirable behavior, we had to add an HTTPS listener to the vhost that we were explicitly using as a catch-all / "junk drawer" for unmatched requests.  (This is what gives you a 404 if you make a request to some app / domain that just doesn't exist.)  Obviously, to do this we needed to provide that "junk drawer" with an SSL cert, just in case the user had not provided there own.  Now if you use HTTPS to make a request to a non-HTTPS enabled app and choose to ignore the cert warning, you see a 404 instead of the content of another app.

So... with the inclusion of that cert being purely a necessary evil, I do not believe we want to modify the router in any way that further encourages its use.

What I can suggest to you as a workaround is that you customize the chart by adding a platform cert.  You may even wish to use a self-signed cert if that's a risk you understand and have chosen for yourself.  We just wouldn't want to impose that choice/risk on Workflow users out-of-the-box.

**Comment by chicagozer** [comment]
Installed a platform cert - working as expected. Thanks!
