### ISSUE TITLE
Need millisecond precision in log format

### ISSUE THREAD

**Issue by jchauncey** [deis/router#181]
Right now the time format isnt precise enough for us to write data into influx. We should be specifying at least millisecond precision. 

See this - https://serverfault.com/questions/732395/can-nginx-log-time-in-iso-8601-format-but-include-milliseconds

**Comment by krancour** [comment]
I don't think it's correct to classify this as a bug.

According to the link above, the options seem to be patching Nginx or running a separate process to do some transformations on the logs.  Both of these seem really ugly.

Is there any possibility that Influx can do anything with `$msec`?  That's just ever-increasing milliseconds since epoch.

**Comment by jchauncey** [comment]
well ill have to turn it into a time object and then send it but yeah it handles it just fine.

**Comment by bacongobbler** [comment]
sounds like this is just an enhancement now... or can we close this?

**Comment by krancour** [comment]
@bacongobbler, I think we need to add `$msec` to the logs, probably right next to the current timestamp.

**Comment by jchauncey** [comment]
we still need to figure this out but we can do this later.

**Comment by jchauncey** [comment]
closing this for now. we handle this differently now with fluentd
