### ISSUE TITLE
Running e2e tests with 60 ginkgo nodes causes issues

### ISSUE THREAD

**Issue by jchauncey** [deis/router#190]
So last night I tried running the e2e tests against a 5 node n1-standard4 GKE cluster with 60 ginkgo nodes. I saw two obvious problems:

1) Huge response time spikes from router - 
<img width="718" alt="screen shot 2016-05-24 at 11 08 07 pm" src="https://cloud.githubusercontent.com/assets/430360/15549155/9083c392-2268-11e6-976a-0fa2b7e18eb3.png">

2) The router is constantly churning because we are creating apps so quickly that it can never fully come up and serve traffic before we hup it again. (This may not be exactly what is happening but it seems that way). This results in us seeing huge numbers of 503s.

**Comment by krancour** [comment]
Addressing no. 1 and no. 2 above separately...

I don't think no. 1 is actually an issue with the router. A slight, but necessary, tangent here... I've looked at the query and the orange trend line is mislabeled. It represents mean; not max. So keep that in mind. (I'll open an issue for that.) Since requests bound for the controller flow through the router, as with any other routable service, the router's max and mean response times reflect not only response times for requests made to applications deployed _via_ workflow, but controller requests as well. The controller takes a lot of traffic in the course of the e2e tests. Many controller requests run longer than the average application request to begin with, but also consider that in this case you have 60 Ginkgo nodes, each making (typically) _multiple_ requests to the controller per spec, and the controller's got only 5 gunicorn threads running. Poor response times from the _controller_ aren't any surprise under these conditions and I believe they're influencing max and mean response times from the router. Especially when you consider the _majority_ of all requests made from the e2e tests are bound for the controller, controller response times have, by far, the most significant influence on the mean response time from the router. Indeed, if I replicate this test, I see a strong correlation between the router's mean and max response times and the response times from the controller itself (upper left-hand graph showing response time by app). If anything, it may be the controller that needs to scale to better accommodate these tests.

Re: no.2:

> The router is constantly churning because we are creating apps so quickly that it can never fully come up and serve traffic before we hup it again. (This may not be exactly what is happening but it seems that way). This results in us seeing huge numbers of 503s.

The router reloads configuration without restarting.  This is from Nginx's own documentation:

> Once the master process receives the signal to reload configuration, it checks the syntax validity of the new configuration file and tries to apply the configuration provided in it. If this is a success, the master process starts new worker processes and sends messages to old worker processes, requesting them to shut down. 

http://nginx.org/en/docs/beginners_guide.html

However, I do not doubt a preponderance of 503s under these circumstances. It is possible that they originate not with the router, but from the kube-proxy. I'm trying to think of how we can test that.

**Comment by jchauncey** [comment]
i wonder if we should make the number of gunicorn threads configurable via an env var and then test it via e2e-runner

**Comment by jchauncey** [comment]
fixed mislabeled alias via - https://github.com/deis/monitor/pull/99

**Comment by jchauncey** [comment]
so we can influence the number of worker threads via - `GUNICORN_WORKERS`  via - https://github.com/deis/controller/blob/master/rootfs/deis/gconf.py#L7

**Comment by krancour** [comment]
Lemme see what happens if I tweak that. Already I'm wondering how we can deal with this gracefully. Is it possible that installing workflow for running e2e tests and for "normal use" require two _different_ configurations? For some reason, that doesn't sit well with me, but I honestly don't know any way around that if our tests are going to put a higher than realistic degree of stress on certain components.

**Comment by jchauncey** [comment]
Sure its totally acceptable that these e2e tests may require a slightly different configuration than the standard one. Specifically because we are trying to run these tests as fast as we possibly cna. This also shakes down some of the configuration params that people might want to tweak in a high load situation.

**Comment by krancour** [comment]
wrt no. 1, the graph doesn't change a whole lot with varying numbers of gunicorn workers in the controller pod, but response times are _always_ low the test applications. If the controller were introducing any latency, I'd expect response times for the the test applications to be affected as well.

As for no. 2, I'm still looking into it.

**Comment by krancour** [comment]
Once again re: no. 1, I'm going to dismiss this as controller requests that (for whatever reason) are actually long-running. I don't believe the router has introduced any latency because I'd expect to see that affect response times for all the test apps as well, but it does not seem to.

No. 2 has remained more elusive. I've spent the whole day attempting to replicate it...

I've tested with two clusters:

* GKE w/ 3 worker nodes (4 vCPU and 15 GB memory each) and k8s 1.2.4
* AWS w/ 3 worker nodes (4 vCPU and 16 GB memory each) and k8s 1.2.0

In both clusters, I deployed [example-go](https://github.com/deis/example-go) as a buildpack app and scaled to 2 instances.

No amount of load placed on either setup using `ab` produced _any_ 5xx errors.

One observation, however, has been that @jchauncey's cluster is pretty old. @kmala has observed difficulties with `kube-proxy` in older clusters. I'm going to keep an eye out for this issue, but I'm pretty confident right now in presuming the issue to be upstream. When we have more data to back us up on that, we can open an issue against Kubernetes.

I'm going to close this for now, as I don't think there's anything actionable here for router itself. I'm happy to re-open this in the future if evidence dictates we do so.
