### ISSUE TITLE
Proposal: drop naxsi application firewall from alpha reqs

### ISSUE THREAD

**Issue by krancour** [deis/router#46]
Generally, we've been shooting for v1.x feature parity with alpha (minus SSL support).  @helgi made a case for also dropping naxsi from alpha and then perhaps slotting in something more fully baked, post alpha.  I'll invite him to elaborate...

**Comment by helgi** [comment]
The short if it is that there are many WAFs out there and we kinda stuck this one (naxsi) in awkwardly there because nginx doesn't have a way to dynamically load new extensions.

nginx 1.10 will have DSO and if we do things correctly on top of that we can let people plug in their own WAF via the DSO + some sort of cusom configuration approach, without having it in our core config.

**Comment by krancour** [comment]
@slack @technosophos any opinions on this?

**Comment by slack** [comment]
Dropping WAF for alpha seems reasonable. Will make sure we track it in the features matrix.

**Comment by krancour** [comment]
Ok.  I'll consider this closed then.  Thanks.
