### ISSUE TITLE
Can we not use JSON in annotations for manually configured things?

### ISSUE THREAD

**Issue by technosophos** [deis/router#63]
Currently we have to manually edit annotations, but annotations are in YAML in JSON even though they are just simple key/value lists:

```
⇒  kdy get rc deis-router
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    chart.helm.sh/description: For testing only!
    chart.helm.sh/file: /Users/mattbutcher/Code/helm_home/workspace/charts/deis/manifests/deis-router-rc.yaml
    chart.helm.sh/name: deis
    chart.helm.sh/version: 2.0.0-pre-alpha
    deis.io/routerConfig: |
      {
        "domain": "10.254.1.3.xip.io",
        "useProxyProtocol": false
      }
```

Is there a reason why we can't simply make these separate annotations?

They are error prone to edit, require additional work to parse, and require additional tooling for things like Helm.

**Comment by helgi** [comment]
How would you propose doing it? `deis.io/routerConfig-domain` (or some sort of a separator). Also will that support things like `list` at the top level?

`annotations` are only one level deep as far as I can gather and it has to be a string (I thought)

**Comment by technosophos** [comment]
Dotted notation works fine for me. I don't even understand why it says "routerConfig" instead of "router". Why not deis.io/router.foo.bar

**Comment by technosophos** [comment]
Or we could do `router.deis.io/foo`

**Comment by helgi** [comment]
Just to be clear, I'm all for doing something that would simplify things as it makes marshalling (and editing) easier on the `workflow` side.

As far as the name, think that's just a hangover in case there was a router annotations that wasn't a config? Seems like that shouldn't be the case tho... Are the dots YAML concepts here I'm not aware off or is that something we'd have to handle in code (Go, Pythong, etc)

**Comment by technosophos** [comment]
I don't know. Dots, dashes, or whatever are fine with me. Personally, I wish Kubernetes had just allowed arbitrarily deep pathing.

**Comment by helgi** [comment]
Agreed, it would make our life a lot easier but I feel like they made a decision around this but I haven't found as to why... Simplicity?

YAML doesn't have anything fancy built in for us to piggy back on

We could move to the dotted structure; I can pretty quickly make a from/to parser in pythong and fix up the `workflow`. If someone takes care of the `router` side to start understanding the new dotted annotations.

Only thing to consider is you can't drop into `deis.io/routerConfig` and work on its contents, you'd have to parser the whole `annotation` structure and do a substring map. Only really a problem if you have A LOT of data to parse through, and we don't :)

I think `router.deis.io/foo.bar.magic` is the best one if we are anyway cleaning it up as we can split on `/` to get the "namespace" of the `annotation`

**Comment by krancour** [comment]
There's a simple reason that I chose this approach.  You don't see it here in the router itself, but in the annotations on an app _service_ that affect router config, one thing we support is a _list_ of domains-- whether they be FQDN's or merely relative to the platform domain.  There is simply no way to do this (currently) in Kubernetes.

Also, nesting can be used to configure certain other router things.  For instance, there are _many_ configurable settings pertaining to gzip.  If you look at router code, these are encapsulated in a `GzipConfig` type, with numerous sensibly defaulted attributes.  This maps directly to ` gzipConfig JSON object.  It's documented here:

https://github.com/deis/router#annotations

Again, there's no way to do something like that in Kubernetes.  Although annotations can allegedly contain structured data, what they really mean by that is that _string_ values may contain structured data that you parse yourself.  JSON was the logical choice for handling that.

I know it looks weird... I'm just saying why it was done.  If we want to change course on this, the proposed solution really needs to account for the need for lists and nested configuration objects.

**Comment by krancour** [comment]
Ok... so my last comment was late at night...

I don't think I accurately conveyed that what is proposed above _will_ work just fine... _as long as_ there can be a way to deal with lists and nested config objects.

The latter can simply be addressed through router code.  For instance `router.deis.io/gzip/compressionLevel` can be understood by the code to be an attribute of the `RouterConfig` object's nested `GzipConfig`.  That's easy enough to do.

The former (lists) is tougher.  I think the answer is to just settle for strings containing comna delimited lists.  This will work fine for the sort of things for which we need a list-- e.g. domains.

I think what happened is that between k8s docs passing mention that annotations may contain structured data and Go's awesome JSON support, I got lured down a path that used those to compensate for the lack of arbitrarily deep pathing in annotations.

Before I OR this (for beta), one question is, are we ok with the repetition of `router.config.io/` as a prefix to every router config setting.  To me, that looks not quite a DRY exception, but very just as out of place in YAML doc as JSON looks.  (One would typucally expect, instead, the very sort of pathing that k8s doesn't allow in annotations.)  As long as we are ok with this, I can start.

**Comment by helgi** [comment]
The dotted approach would be `router.deis.io/gzip.compressionLevel.foobar = tralala` - in that mode we'd split off at `/` and then the real nested behaviour is discovered from `.`, so in that case `['gzip']['compressionLevel']['foobar'] = tralalala`; However your approach with `/` is also good and in fact would allow us to use more path split/join type mechanisms if that was a benefit but early in the morning it looked odd two think about the left side and the right side as having distinct purposes. Thoughts?

Beyond that `list` was our biggest dealio; The way I'd solve that initially is to turn it into a comma separated string, like you suggested. The code just needs to know that is suppose to be a list instead of a string containing a comma (as in lets not try to be too smart off the bat).

So with the above two, I think we are on the same page. I just wanted to reason it out the way I saw it :) 

I'm okay with the repeating if it makes everyone else life easier, both on `helm` and general tinkering directly on a manifest (as is the current `deis` instructions). I think JSON made it potentially powerful (and I would have done what we did) but perhaps not what we needed in the end.

@krancour you and I should have a look at `ConfigMap` more closely and see if it solve this whole thing for us as we may be able to piggyback off that sooner than we think for the end of beta / stable if timelines align

**Comment by krancour** [comment]
Ya.  I was avoiding ConfigMap because it would rule out using k8s 1.1.  I've seen other suggestions floating around already that might make k8s 1.2 our minimum target.  It'd be good to know whether we're going that direction or not, becausr it obviously affects how we choose to handle things like this.

But for the moment, yes... I think we're on the same page in terms of how we can improve this in the near term / beta timeframr.

**Comment by helgi** [comment]
I'd say it's more likely than not we end up with 1.2 as a minimum than not for v2 stable but that also assumes ConfigMap is stable then instead of 1.3, 1.4 etc :)

IMO lets go with what we just talked about and keep an eye on what ConfigMap gives us and if we have a viable migration story.

So do we prefer:
* `router.deis.io/gzip/foo.bar` where everything is `/` and first portion just get discarded
* `router.deis.io/gzip.foo.bar` where `/` separates the components from configuration and `.` is for nesting

**Comment by krancour** [comment]
I think I prefer slashes as delimiters, but idk how much it will ultimately matter.  Since annotations are _actually_ flat, those are really all just strings.

So router code, for instance, can determine whether proxy protocol is enabled via something like this:

```
const keyPrefix = "router.deis.io"

# ...

routerConfig.UseProxyProtocol = annotations[getKey("useProxyProtocol")]

# ...

func getKey(key string) string {
  return fmt.Sprintf("%s/%s", keyPrefix, key)
}
```

**Comment by krancour** [comment]
But... it does matter to the extent that router and workflow need to agree.  I vote slashes.

**Comment by technosophos** [comment]
ridiculously enough, k8s limits you to one slash in an annotation name.

**Comment by krancour** [comment]
Ugh.  Dots then?  @helgi

**Comment by helgi** [comment]
yah, dots. lets use the `/` to separate the namespace from the keys
