### ISSUE TITLE
Add stats endpoint back to router

### ISSUE THREAD

**Issue by jchauncey** [deis/router#98]
It would be awesome if we could add this back but bind it to localhost.

**Comment by krancour** [comment]
I'm ok with that in theory, but the tricky thing about this that we can only pick what IP _nginx_ binds to.  I could be wrong, but I don't think there's any way to bind individual vhosts (server blocks) to specific IPs.

What if I could achieve the same thing through a different trick?  What if I were to use the `allow` and `deny` directives to allow incoming requests to the stats endpoint from `127.0.0.1` only and drop all others?  Would that help?

**Comment by jchauncey** [comment]
sure as long as I can access it from within the pod

**Comment by krancour** [comment]
Would you care if it ended up on port 9090?  I expose a server there that _never_ uses proxy protocol (this is mainly for the sake of HTTP-based healthchecks from load balancers) since the default server may or may not be using it.  We wouldn't want that in play if you're making an HTTP request from within the pod, so adding the stats endpoint to the default server on 9090 would ensure that.

**Comment by jchauncey** [comment]
Nope as long as its always that port we should be fine. Granted this might have to change slightly when I get around to pulling stats from this but for now it should work.

**Comment by krancour** [comment]
Possibly related to #90
